Use Pipenv on GitHub action workflow (#24)
### Description
We're getting a ResolutionImpossible error on the GitHub action
execution, despite there hasn't been any dependency change recently
Full error message:

```
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
The conflict is caused by:
    The user requested idna==2.9
    moto 1.3.14 depends on idna<2.9 and >=2.5
```

Besides, we're trying to install the same dependencies that are working
perfectly fine on local environments, so there cannot be any problem
with the dependencies

The workflow should work perfectly fine because we're using the same dependencies than in the local environment, so this probably is a problem with the pip resolver. There are a few similar issues open on their main repo so it's definitely a possibility.

In any case, to avoid having to worry about two different dependency management systems, Pipenv locally and pip on GH Actions, we'll change the latter to use Pipenv too