Upgrade Pip on GitHub action workflow
We're getting a ResolutionImpossible error on the GitHub action
execution, despite there hasn't been any dependency change recently
Full error message:

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
The conflict is caused by:
    The user requested idna==2.9
    moto 1.3.14 depends on idna<2.9 and >=2.5

Besides, we're trying to install the same dependencies that are working
perfectly fine on local environments, so there cannot be any problem
with the dependencies

Apparently the pip version GH Actions is using used a new resolver and
there were a few issues from people claiming to have the same issue.
The goal of this change is to make sure that we're using the last pip
version in case this was a bug that has already been fixed